### ISSUE TITLE
Docker image latest erkennt nicht HM-MOD-RPI-PCB

### ISSUE THREAD

**Issue by lukicsl** [jens-maus/RaspberryMatic#1448]
**Describe the bug**
bei der Version des docker image raspberrymatic:3.59.6.20211009 wird das HM-MOD-RPI-PCB modul nicht erkannt 

**Steps to reproduce the behavior**
1. Jungfreuliche installation raspberry pi os 32-bit
2. sudo apt-get udate/upgrade
3. docker installation mit get-docker.sh
4. installation raspberrymatit mit deploy.sh

**Expected behavior**
raspberrymatic startet und HM-MOD-RPI-PCB wird erkannt

**Screenshots**
HM-MOD-RPI-PCB wird nicht erkannt
![image](https://user-images.githubusercontent.com/23736716/136896182-f125240d-b677-4838-a37a-a442d9ee2863.png)

**System information:**
 - RaspberryMatic Version: docker version <latest> (3.59.6.20211009)
 - Used Hardware: raspberry pi 4/4GB
 - Used HomeMatic RF-Module: HM-MOD-RPI-PCB direkt auf GPIO

**Additional context**
Ich habe zum Versuch auch eine SD-Kartenbasierte Vollversion auf dieselbe HW installiert **und das HM-MOD-RPI-PCB wird erkannt, es liegt kein HW problem vor**

Ich habe auch das älteste verfügbare image (raspberrymatic:3.59.6.20210901-f3d23b9) in der container registry geladen, und das funktioniert auch nicht:
![image](https://user-images.githubusercontent.com/23736716/136897667-74c13e3d-a0cc-4aa2-906b-d9708b3ff872.png)

**Comment by lukicsl** [comment]
Mit diesem docke-compose.yaml funktioniert es nun:
```
version: "3.8"
services:
  raspberrymatic:
    image: ghcr.io/jens-maus/raspberrymatic:latest
    container_name: ccu
    hostname: homematic-raspi
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - ccu_data:/usr/local:rw
      - /lib/modules:/lib/modules:ro
      - /run/udev/control:/run/udev/control
    ports:
      - "8080:80"
      - "2001:2001"
      - "2010:2010"
      - "9292:9292"
      - "8181:8181"
volumes:
  ccu_data:
```
