### ISSUE TITLE
Docker Image 3.59.6.20211009 HB-RF-ETH nicht unterstützt

### ISSUE THREAD

**Issue by lukicsl** [jens-maus/RaspberryMatic#1483]
**Describe the bug**
Ich habe den neuesten docker container geladen und die Unterstützung vom HB-RF-ETH funktioniert nicht

**Steps to reproduce the behavior**
1. Docker image laden  und in /etc/config/hb_rf_eth die ip adresse vom HB-RF-ETH eintrage
2. Neustarten
3. startup log analysiern -> docker logs -f ccu

**Expected behavior**
Das HB-RF-ETH wird eigebunden

**Fehlerlogausgabe**
ccu               | Starting watchdog...
ccu               | Identifying onboard hardware: oci, OK
ccu               | Initializing RTC Clock: no hardware found
ccu               | Running sysctl: OK
ccu               | Checking for Factory Reset: not required
ccu               | Checking for Backup Restore: not required
ccu               | Initializing System: OK
ccu               | Starting logging: OK
ccu               | Populating /dev using udev: done
ccu               | Init onboard LEDs: init, OK
ccu               | Starting irqbalance: OK
ccu               | Starting network: eth0: link up, fixed, firewall, inet up, 172.18.0.2, OK
ccu               | Identifying Homematic RF-Hardware: modprobe: can't change directory to '**/lib/modules**': No such file or directory
ccu               | .............................../etc/init.d/S47InitRFHardware: line 58: can't create /sys/module/hb_rf_eth/parameters/connect: nonexistent directory
ccu               | /etc/init.d/S47InitRFHardware: line 58: can't create /sys/module/hb_rf_eth/parameters/connect: nonexistent directory
ccu               | ./etc/init.d/S47InitRFHardware: line 58: can't create /sys/module/hb_rf_eth/parameters/connect: nonexistent directory

**System information:**
 - RaspberryMatic Version: docker version <latest> (3.59.6.20211009)
 - Used Hardware: raspberry pi 4/4GB
 - Used HomeMatic RF-Module: HM-MOD-RPI-PCB direkt auf GPIO

**Additional context**
Auf dem docker image gibt es kein Verzeichnis /lib/modules
Ich habe die selbe Version des Raspberrymatic als sd-karten-Version installiert und das entsprechende Verzeichnis ist vorhande. Nach der Konfiguration wird das HB-RF-ETH erkannt und eingebunden.

**Comment by jens-maus** [comment]
Bitte zeigen wie du den docker container konkret startest und bitte klären ob du die benötigten kernel module im host system wie in der Anleitung auch installiert hast.

**Comment by lukicsl** [comment]
Ich lade das docke image mittels folgendem docke-compose.yaml:

```
version: "3"
services:
  raspberrymatic:
    image: ghcr.io/jens-maus/raspberrymatic:latest
    container_name: ccu
    hostname: homematic-raspi
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /datavol/homematic/ccu_data/:/usr/local:rw
    ports:
      - "8090:80"
      - "8022:22"
      - "2001:2001"
      - "2010:2010"
      - "9292:9292"
      - "8181:8181"

```
ich habe alle kernel module istalliert wie es in der Beschreibung angegeben ist.
Auf dem Hostsystem ist auch das Verzeichnis /lib/modules vorhanden. Auf dem docker image aber nicht.
