### ISSUE TITLE
Update bootstrap v3.4 to v4.6 in 0057-WebUI-ImprovedDutyCycleDisplay

### ISSUE THREAD

**Issue by ptweety** [jens-maus/RaspberryMatic#1509]
### Describe the solution you'd like

This is an idea to make future updates simpler and more straight forward!

In `0057-WebUI-ImprovedDutyCycleDisplay` we introduced [bootstrap](https://getbootstrap.com) into **RasperryMatic** and included bootstrap v3.4. I would like to have an update to v4.6 and separate bootstrap into it's own patch. I think there are the following steps required:

**0002-WebUI-Bootstrap-Setup:**
- Introduce a new WebUI patch (e.g. 0002-WebUI-Bootstrap-Setup)
- Add bootstrap files to this patch (e.g. `www/webui/css/extern/` -> `bootstrap.min.css`, `bootstrap.min.css.orig`, `bootstrap.min.css.map`, `bootstrap.min.css.map.orig`, `www/webui/js/extern/` -> `bootstrap.min.js`, `bootstrap.min.js.orig`, `bootstrap.min.js.map`, `bootstrap.min.js.map.orig`)
- Prepare for our custom bootstrap styles in an empty file `www/webui/css/extern/hmBootstrap.css`
- Load the `css` and `js` in `/www/rega/pages/index.htm`:
  ```diff
    <link rel="stylesheet" type="text/css" href="/webui/css/extern/spectrum.css" />
  + <link rel="stylesheet" type="text/css" href="/webui/css/extern/bootstrap.min.css" />
  + <link rel="stylesheet" type="text/css" href="/webui/css/extern/hmBootstrap.css" />
    <link id="idCss" rel="stylesheet" type="text/css" href="/webui/style.cgi" />
  ...
    <script type="text/javascript" src="/webui/js/extern/jquery.js"></script>
  + <script type="text/javascript" src="/webui/js/extern/bootstrap.min.js"></script>
    <script type="text/javascript" src="/webui/js/extern/jqueryURLPlugin.js"></script>
  ```

**0006-WebUi-Bootstrap-Fixes:**
- Introduce a new WebUI path (e.g. 0006-WebUi-Bootstrap-fixes)
- fix `style.cgi` by adding `box-sizing: content-box;`to `#menubar`

**0057-WebUI-ImprovedDutyCycleDisplay:**
- Remove all the bootstrap files from this patch
- Remove loading of `css` and `js` in `/www/rega/pages/index.htm` from this patch
- Rework the styles in the current `hmBootstrap.css`and reduce them to the needed ones:
  ```css
  #hmBootstrap .progress {
    position: relative; /* inserted */
    height: 14px; /* 20px */
    /* margin-bottom: 20px; /* removed */
  }
  #hmBootstrap .progress span {
      position: absolute;
      display: block;
      width: 100%;
      color: black;
  }
  #hmBootstrap .progress-bar {
    font-size: 11px; /* 12px */
    line-height: 14px; /* 20px */
  }
  ```

### Describe alternatives you've considered

n/a

### Is your feature request related to a problem?

No

### Additional information

Since this is not a simple change I'd like to discuss it upfront with the original authors of the `0057-WebUI-ImprovedDutyCycleDisplay` patch.

@jp112sdl : I'd like to have your advice on this topic. Can you please review the proposed steps? I also had a hard time to identify the required style change in your original `hmBootstrap.css`. You may also review these ...

@jens-maus : The definition and naming of such new patch files is beyond my competencies. Also the whole process of reworking patches down the line from `#0001` to `#01xx` is to complicated for my humble brain. Can you please advice as well?
