### ISSUE TITLE
Container does no start after docker host reboot

### ISSUE THREAD

**Issue by TheUntouchable** [jens-maus/RaspberryMatic#1790]
### Describe the issue you are experiencing

If I am rebooting my docker host (Docker version 20.10.14, build a224086, RaspberryPI 4 8GB, RaspberryOS bullseye) raspberrymatic container does not start after the reboot is finished. Its set to restart always. Docker message is "Stopped for a minute with exit code 129".

### Describe the behavior you expected

The docker container should start by itself after the docker host is rebooted

### Steps to reproduce the issue

1. Restart the docker host
2. Wait
3. No profit (container does not start)

### What is the version this bug report is based on?

3.63.8.20220330

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
I don't know what exactly could be userfull, perhaps you can tell me what I should look for.
```

### Additional information

docker-compse I use:

```
version: "3.8"
services:
  raspmatic:
    image: ghcr.io/jens-maus/raspberrymatic:latest
    container_name: raspmatic
    hostname: nw-raspmatic
    privileged: true
    restart: always
    stop_grace_period: 30s
    volumes:
      - NFS_raspmatic_data:/usr/local:rw
      - /lib/modules:/lib/modules:ro
      - /run/udev/control:/run/udev/control
    mac_address: 02:42:c0:a8:3c:04
    networks:
      MACVLAN_NETW_VLAN60_Docker_Container:
        ipv4_address: 192.168.60.4
      
volumes:
  NFS_raspmatic_data:
    external: true

networks:
  MACVLAN_NETW_VLAN60_Docker_Container:
    external: true

```
