### ISSUE TITLE
Cannot access web UI with Docker.

### ISSUE THREAD

**Issue by Yukicanis** [jens-maus/RaspberryMatic#1946]
### Describe the issue you are experiencing

I set up RaspberryMatic using docker-compose as follows:

```
  raspberrymatic:
    container_name: raspberrymatic
    image: ghcr.io/jens-maus/raspberrymatic:3.65.8.20220831
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - ./ccu_data:/usr/local:rw
      - /lib/modules:/lib/modules:ro
      - /run/udev/control:/run/udev/control
    ports:
      - "8081:80"
      - "2001:2001"
      - "2010:2010"
      - "9292:9292"
      - "8181:8181"
```

In the RaspberryMatic logs I noticed an error about `multimacd` (see below) and I cannot access the web UI, which should be accessible via port 8081 in my case. According to wireshark the HTTP server accepts the TCP connection but doesn't answer the GET request.

### Describe the behavior you expected

Being able to access the web UI.

### Steps to reproduce the issue

1. Install RaspberryMatic using docker-compose.
2. Try to access the web UI.
3.
...

### What is the version this bug report is based on?

3.65.8.20220831

### Which base platform are you running?

odroid-n2 (ODROID N2/N2+)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Populating /dev using udev: done
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.18.0.2, OK
Identifying Homematic RF-Hardware: ....HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-xhci-hcd.0.auto-1.2.4, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-xhci-hcd.0.auto-1.2.4, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.18, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: ..........ERROR
Starting rfd: ERROR: /dev/mmd_bidcos missing, no BidCos-RF hardware found
Starting HMIPServer: ERROR: /dev/mmd_hmip missing
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
find: /usr/local/etc/monit*.cfg: No such file or directory
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.65.8.20220831 (raspmatic_oci_arm64)
```

### Additional information

Host OS is Arch Linux Arm with kernel 5.10.2-6-ARCH.
