### ISSUE TITLE
"else" element in ccu programs have the wrong color

### ISSUE THREAD

**Issue by HolgerJeromin** [jens-maus/RaspberryMatic#995]
**Describe the bug**
In a ccu program we have different background colors for each if and elseif blocks. They are encapsuled in `class="conditionOdd"` and `class="conditionEven"` HTMLDivElements.

But initially the "else" branch is not put into another HTMLDivElement, but attached to the last one.

This results in a wrong background color:
![image](https://user-images.githubusercontent.com/2410353/99887503-39432780-2c45-11eb-8920-43f1be0d9e3d.png)
The last block should have been dark. This is fixed when you click on the last green plus. The DOM is reloaded and a correct new DivElement is created.

A clean solution should always create a new HTMLDivElement, but a small CSS hack can be done to fix it. We only ever have two `.Rule` elements. So when we have a third one this does not belong here and we can fix its color with this code:
```css
.conditionOdd > .Rule:nth-child(3) {
    background-color: #bcc7cb;
}
.conditionEven > .Rule:nth-child(3) {
    background-color: #ebf1f2;
}
```

I have no idea how to inject such a CSS file but I am happy to provide a PR if you can give me a small hint.

**System information:**
 - RaspberryMatic Version: 3.53.30.20201024
 - Used Hardware: ccu3
